-- Provisional weapons data generated from image files
-- Generated on 2025-10-06T08:30:30.509Z

INSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhqiw8poeg5z',
  'Chirping Cicada',
  'chirping-cicada',
  5,
  'Auto Crossbow',
  1184,
  'Impact',
  'Solar',
  'Power',
  '/images/weapons/autocrossbow/chirping-cicada.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhyc4ewxa2w7l',
  'Hon3 Eibellakks',
  'hon3-eibellakks',
  3,
  'Auto Crossbow',
  1411,
  'Spread',
  'Arc',
  'Primary',
  '/images/weapons/autocrossbow/hon3-eibellakks.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhu8ui4geqiy',
  'Mahamayuri',
  'mahamayuri',
  4,
  'Auto Crossbow',
  1257,
  'Spread',
  'Arc',
  'Power',
  '/images/weapons/autocrossbow/mahamayuri.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhu7aqq6czkkc',
  'P45 Turbot',
  'p45-turbot',
  6,
  'Auto Crossbow',
  1137,
  'Piercing',
  'Arc',
  'Primary',
  '/images/weapons/autocrossbow/p45-turbot.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhu3gkw68dex',
  'Saizo',
  'saizo',
  6,
  'Auto Crossbow',
  1480,
  'Impact',
  'Arc',
  'Primary',
  '/images/weapons/autocrossbow/saizo.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhgt4tmul6w2m',
  'Cognitum Carbine',
  'cognitum-carbine',
  6,
  'Auto Rifle',
  1390,
  'Spread',
  'Void',
  'Primary',
  '/images/weapons/autorifles/cognitum-carbine.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh6rznrf9y05l',
  'P22 Tamarin',
  'p22-tamarin',
  6,
  'Auto Rifle',
  1427,
  'Impact',
  'Arc',
  'Primary',
  '/images/weapons/autorifles/p22-tamarin.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhichf7ao9c2',
  'Sweet Business',
  'sweet-business',
  5,
  'Auto Rifle',
  1432,
  'Rapid-Fire',
  'Solar',
  'Power',
  '/images/weapons/autorifles/sweet-business.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh7veqrsuz7wk',
  'Sworn Oath',
  'sworn-oath',
  6,
  'Auto Rifle',
  1020,
  'Rapid-Fire',
  'Arc',
  'Primary',
  '/images/weapons/autorifles/sworn-oath.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhqvm5zzo80ki',
  'Toxic Equation',
  'toxic-equation',
  4,
  'Auto Rifle',
  1192,
  'Piercing',
  'Solar',
  'Primary',
  '/images/weapons/autorifles/toxic-equation.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh7916pei4uxu',
  'Type 301 1 Sri',
  'type-301-1-sri',
  5,
  'Auto Rifle',
  1081,
  'Rapid-Fire',
  'Solar',
  'Power',
  '/images/weapons/autorifles/type-301-1-sri.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh4o381bsv9vr',
  'Ist1 Parantha',
  'ist1-parantha',
  4,
  'Fusion Rifle',
  1023,
  'Piercing',
  'Solar',
  'Power',
  '/images/weapons/fusionrifles/ist1-parantha.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh0sg0lhg91h3',
  'Jotunn',
  'jotunn',
  5,
  'Fusion Rifle',
  1480,
  'Spread',
  'Arc',
  'Power',
  '/images/weapons/fusionrifles/jotunn.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh37nfotxofp1',
  'Mutineers Torch',
  'mutineers-torch',
  6,
  'Fusion Rifle',
  1263,
  'Rapid-Fire',
  'Void',
  'Power',
  '/images/weapons/fusionrifles/mutineers-torch.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhss88nrjqwaj',
  'Rev 7 Fusillade',
  'rev-7-fusillade',
  5,
  'Fusion Rifle',
  1009,
  'Rapid-Fire',
  'Solar',
  'Primary',
  '/images/weapons/fusionrifles/rev-7-fusillade.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhzbqlk9deuzg',
  'The Monolith',
  'the-monolith',
  3,
  'Fusion Rifle',
  1495,
  'Spread',
  'Solar',
  'Primary',
  '/images/weapons/fusionrifles/the-monolith.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh63jwjrq71w7',
  '6g76 Self Rescue Lvl',
  '6g76-self-rescue-lvl',
  5,
  'Grenade Launcher',
  1264,
  'Spread',
  'Solar',
  'Primary',
  '/images/weapons/grenadelaunchers/6g76-self-rescue-lvl.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nheqmo6ih6rs',
  'A112 Calf',
  'a112-calf',
  4,
  'Grenade Launcher',
  1205,
  'Spread',
  'Void',
  'Primary',
  '/images/weapons/grenadelaunchers/a112-calf.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhf7goha01k4r',
  'Hon1 Khanom Khrok',
  'hon1-khanom-khrok',
  4,
  'Grenade Launcher',
  1212,
  'Spread',
  'Void',
  'Power',
  '/images/weapons/grenadelaunchers/hon1-khanom-khrok.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhkbef83ry1l',
  'Prompt Satellite Dispenser',
  'prompt-satellite-dispenser',
  5,
  'Grenade Launcher',
  1466,
  'Spread',
  'Solar',
  'Power',
  '/images/weapons/grenadelaunchers/prompt-satellite-dispenser.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhuzz0vh8h37k',
  'Satiyaaliksni Smart Bomb',
  'satiyaaliksni-smart-bomb',
  5,
  'Grenade Launcher',
  1036,
  'Rapid-Fire',
  'Solar',
  'Primary',
  '/images/weapons/grenadelaunchers/satiyaaliksni-smart-bomb.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhke2dz7vik5b',
  'Amatoxin',
  'amatoxin',
  3,
  'Hand Cannon',
  1323,
  'Rapid-Fire',
  'Arc',
  'Primary',
  '/images/weapons/handcannons/amatoxin.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhcke0db68cfj',
  'Aocs R1 Revolver',
  'aocs-r1-revolver',
  5,
  'Hand Cannon',
  1161,
  'Spread',
  'Solar',
  'Primary',
  '/images/weapons/handcannons/aocs-r1-revolver.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhp7bvpsn25m',
  'Crimson',
  'crimson',
  3,
  'Hand Cannon',
  1130,
  'Impact',
  'Solar',
  'Power',
  '/images/weapons/handcannons/crimson.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh2gnm6re6imp',
  'Del7 Simit',
  'del7-simit',
  3,
  'Hand Cannon',
  1042,
  'Piercing',
  'Arc',
  'Power',
  '/images/weapons/handcannons/del7-simit.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhktc0d5119we',
  'P6 Somniosus',
  'p6-somniosus',
  3,
  'Hand Cannon',
  1343,
  'Spread',
  'Void',
  'Primary',
  '/images/weapons/handcannons/p6-somniosus.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhgb90l7t4u3n',
  'Survivors Instinct',
  'survivors-instinct',
  3,
  'Hand Cannon',
  1082,
  'Spread',
  'Solar',
  'Power',
  '/images/weapons/handcannons/survivors-instinct.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhaa8mbkvc9oh',
  'The Old Prefect',
  'the-old-prefect',
  5,
  'Hand Cannon',
  1104,
  'Spread',
  'Solar',
  'Power',
  '/images/weapons/handcannons/the-old-prefect.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhzhgs258uqq',
  'Brotherhoods Banner',
  'brotherhoods-banner',
  5,
  'Light Grenade Launcher',
  1098,
  'Impact',
  'Solar',
  'Primary',
  '/images/weapons/lightgrenadelaunchers/brotherhoods-banner.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhvsy79vfzvpn',
  'Laplaces Mystery',
  'laplaces-mystery',
  6,
  'Light Grenade Launcher',
  1372,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/lightgrenadelaunchers/laplaces-mystery.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nha8b0fii6aok',
  'Lotus',
  'lotus',
  3,
  'Light Grenade Launcher',
  1125,
  'Rapid-Fire',
  'Arc',
  'Primary',
  '/images/weapons/lightgrenadelaunchers/lotus.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhsk1st14ylg8',
  'Present Fleet',
  'present-fleet',
  4,
  'Light Grenade Launcher',
  1359,
  'Spread',
  'Void',
  'Primary',
  '/images/weapons/lightgrenadelaunchers/present-fleet.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh5z5o182wrnp',
  'End Of The Line',
  'end-of-the-line',
  5,
  'Linear Fusion Rifle',
  1480,
  'Spread',
  'Arc',
  'Power',
  '/images/weapons/linearfusionrifles/end-of-the-line.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh986ghbhiasi',
  'Latitude',
  'latitude',
  4,
  'Linear Fusion Rifle',
  1464,
  'Piercing',
  'Arc',
  'Power',
  '/images/weapons/linearfusionrifles/latitude.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhic7qmy2afs',
  'Royal Contravene',
  'royal-contravene',
  5,
  'Linear Fusion Rifle',
  1257,
  'Impact',
  'Void',
  'Primary',
  '/images/weapons/linearfusionrifles/royal-contravene.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhpd6fwv9v4gs',
  'Tye Nurler Ao4',
  'tye-nurler-ao4',
  3,
  'Linear Fusion Rifle',
  1081,
  'Spread',
  'Void',
  'Power',
  '/images/weapons/linearfusionrifles/tye-nurler-ao4.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhypa6gnok9td',
  'Bvd4 Akutaak',
  'bvd4-akutaak',
  4,
  'Machine Gun',
  1222,
  'Rapid-Fire',
  'Void',
  'Primary',
  '/images/weapons/machineguns/bvd4-akutaak.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhr0j7vrq299',
  'Chilling Thrill',
  'chilling-thrill',
  4,
  'Machine Gun',
  1020,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/machineguns/chilling-thrill.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh15z102lufa2',
  'Full Field Thresher',
  'full-field-thresher',
  4,
  'Machine Gun',
  1443,
  'Spread',
  'Solar',
  'Primary',
  '/images/weapons/machineguns/full-field-thresher.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhoxesnyt2mg',
  'Gallows',
  'gallows',
  3,
  'Machine Gun',
  1130,
  'Rapid-Fire',
  'Solar',
  'Primary',
  '/images/weapons/machineguns/gallows.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh68oz5otde4d',
  'Heir Apparent',
  'heir-apparent',
  3,
  'Machine Gun',
  1495,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/machineguns/heir-apparent.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhryolywzvquh',
  'Scorched Earth',
  'scorched-earth',
  4,
  'Machine Gun',
  1255,
  'Piercing',
  'Solar',
  'Primary',
  '/images/weapons/machineguns/scorched-earth.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhsh5hpxdzphn',
  'Spikefling Baton',
  'spikefling-baton',
  3,
  'Machine Gun',
  1202,
  'Piercing',
  'Solar',
  'Power',
  '/images/weapons/machineguns/spikefling-baton.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh4c7q5oif1dq',
  'Del2 Sweet Ears',
  'del2-sweet-ears',
  4,
  'Pulse Rifle',
  1302,
  'Rapid-Fire',
  'Arc',
  'Power',
  '/images/weapons/pulserifles/del2-sweet-ears.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhzc8q3yuwjkp',
  'Furies Iii',
  'furies-iii',
  3,
  'Pulse Rifle',
  1334,
  'Rapid-Fire',
  'Void',
  'Power',
  '/images/weapons/pulserifles/furies-iii.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh693ckz2m90j',
  'Kabr',
  'kabr',
  3,
  'Pulse Rifle',
  1419,
  'Rapid-Fire',
  'Void',
  'Power',
  '/images/weapons/pulserifles/kabr.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhkcoo1ja627',
  'P31 Armadillo',
  'p31-armadillo',
  6,
  'Pulse Rifle',
  1280,
  'Impact',
  'Solar',
  'Primary',
  '/images/weapons/pulserifles/p31-armadillo.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhir98vxsih2',
  'Reverse Equilibrium',
  'reverse-equilibrium',
  4,
  'Pulse Rifle',
  1408,
  'Spread',
  'Void',
  'Power',
  '/images/weapons/pulserifles/reverse-equilibrium.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhynz4kuo5bp',
  'Type 7 Moonshot Emr M',
  'type-7-moonshot-emr-m',
  5,
  'Pulse Rifle',
  1292,
  'Spread',
  'Arc',
  'Power',
  '/images/weapons/pulserifles/type-7-moonshot-emr-m.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh1aphdbq41po',
  'Ultimatum',
  'ultimatum',
  4,
  'Pulse Rifle',
  1350,
  'Impact',
  'Solar',
  'Power',
  '/images/weapons/pulserifles/ultimatum.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh2sk4z3vh3m',
  'A67 Javan Rhino',
  'a67-javan-rhino',
  5,
  'Rocket Launcher',
  1098,
  'Spread',
  'Arc',
  'Power',
  '/images/weapons/rocketlaunchers/a67-javan-rhino.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhnnp3af1m38',
  'Call Of Greed',
  'call-of-greed',
  6,
  'Rocket Launcher',
  1107,
  'Spread',
  'Arc',
  'Power',
  '/images/weapons/rocketlaunchers/call-of-greed.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhjd7kkklskza',
  'Hon2 Tutumalik',
  'hon2-tutumalik',
  4,
  'Rocket Launcher',
  1210,
  'Rapid-Fire',
  'Void',
  'Power',
  '/images/weapons/rocketlaunchers/hon2-tutumalik.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhjggs84evqr',
  'J90 Hornbill',
  'j90-hornbill',
  4,
  'Rocket Launcher',
  1302,
  'Rapid-Fire',
  'Void',
  'Power',
  '/images/weapons/rocketlaunchers/j90-hornbill.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhh5komdnkvan',
  'Two Tailed Fox',
  'two-tailed-fox',
  3,
  'Rocket Launcher',
  1130,
  'Spread',
  'Void',
  'Power',
  '/images/weapons/rocketlaunchers/two-tailed-fox.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh0lvqktzimn9',
  'Always Going Home',
  'always-going-home',
  5,
  'Scout Rifle',
  1187,
  'Impact',
  'Void',
  'Primary',
  '/images/weapons/scoutrifles/always-going-home.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhx515ltioww',
  'Del3 Lassi',
  'del3-lassi',
  5,
  'Scout Rifle',
  1314,
  'Impact',
  'Void',
  'Primary',
  '/images/weapons/scoutrifles/del3-lassi.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhbt0i02br0s',
  'Fall From Grace',
  'fall-from-grace',
  4,
  'Scout Rifle',
  1140,
  'Impact',
  'Arc',
  'Primary',
  '/images/weapons/scoutrifles/fall-from-grace.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhzjwkxdini08',
  'P267 Right Whale',
  'p267-right-whale',
  6,
  'Scout Rifle',
  1274,
  'Piercing',
  'Arc',
  'Power',
  '/images/weapons/scoutrifles/p267-right-whale.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhncxd0hpmt8g',
  'Polaris Lance',
  'polaris-lance',
  6,
  'Scout Rifle',
  1024,
  'Impact',
  'Void',
  'Primary',
  '/images/weapons/scoutrifles/polaris-lance.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh9txcrobauh',
  'Total Lockdown',
  'total-lockdown',
  5,
  'Scout Rifle',
  1191,
  'Piercing',
  'Void',
  'Primary',
  '/images/weapons/scoutrifles/total-lockdown.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhgkb7rgowwn6',
  'Eternal Retribution',
  'eternal-retribution',
  4,
  'Shotgun',
  1353,
  'Impact',
  'Void',
  'Primary',
  '/images/weapons/shotguns/eternal-retribution.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhg5rh15bih7g',
  'Gunpowder Duster',
  'gunpowder-duster',
  4,
  'Shotgun',
  1255,
  'Rapid-Fire',
  'Void',
  'Power',
  '/images/weapons/shotguns/gunpowder-duster.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhn4izuukxcxf',
  'Ist2 Niaatiks',
  'ist2-niaatiks',
  4,
  'Shotgun',
  1046,
  'Rapid-Fire',
  'Solar',
  'Primary',
  '/images/weapons/shotguns/ist2-niaatiks.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhycduvwao05',
  'K205 Lemming',
  'k205-lemming',
  5,
  'Shotgun',
  1480,
  'Spread',
  'Arc',
  'Primary',
  '/images/weapons/shotguns/k205-lemming.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh4wwloe5z1n4',
  'Labyrinths Compass',
  'labyrinths-compass',
  5,
  'Shotgun',
  1462,
  'Impact',
  'Void',
  'Power',
  '/images/weapons/shotguns/labyrinths-compass.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhsfgemxeaxpd',
  'Octant Riot Disperser',
  'octant-riot-disperser',
  6,
  'Shotgun',
  1087,
  'Impact',
  'Arc',
  'Primary',
  '/images/weapons/shotguns/octant-riot-disperser.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhyg4hy4gb27',
  'Sandan 54 Fieldhand',
  'sandan-54-fieldhand',
  5,
  'Shotgun',
  1235,
  'Piercing',
  'Arc',
  'Primary',
  '/images/weapons/shotguns/sandan-54-fieldhand.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh6kirjj9bzil',
  'The Chaperone',
  'the-chaperone',
  3,
  'Shotgun',
  1427,
  'Piercing',
  'Void',
  'Power',
  '/images/weapons/shotguns/the-chaperone.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh1d3uqvun0hfk',
  'Azure Drab Auto Fab',
  'azure-drab-auto-fab',
  5,
  'Sidearm',
  1074,
  'Piercing',
  'Void',
  'Primary',
  '/images/weapons/sidearms/azure-drab-auto-fab.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh2n8onpyaq1q',
  'Century Lookout',
  'century-lookout',
  5,
  'Sidearm',
  1002,
  'Rapid-Fire',
  'Solar',
  'Power',
  '/images/weapons/sidearms/century-lookout.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh2pw0ozmvm87',
  'Chushingura',
  'chushingura',
  4,
  'Sidearm',
  1393,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/sidearms/chushingura.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhv7atxl4hgco',
  'Concerto',
  'concerto',
  4,
  'Sidearm',
  1346,
  'Piercing',
  'Void',
  'Primary',
  '/images/weapons/sidearms/concerto.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhtlmb9owv7gd',
  'Del6 Kokoretsi',
  'del6-kokoretsi',
  5,
  'Sidearm',
  1086,
  'Rapid-Fire',
  'Void',
  'Power',
  '/images/weapons/sidearms/del6-kokoretsi.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh7x63hewnaen',
  'Permanent Liability',
  'permanent-liability',
  3,
  'Sidearm',
  1185,
  'Impact',
  'Arc',
  'Primary',
  '/images/weapons/sidearms/permanent-liability.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh8vk52q4xhtk',
  '40000 Sidereal Year',
  '40000-sidereal-year',
  4,
  'Sniper Rifle',
  1103,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/sniperrifles/40000-sidereal-year.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhit09pbkc33h',
  'A19 Argali',
  'a19-argali',
  3,
  'Sniper Rifle',
  1372,
  'Spread',
  'Void',
  'Power',
  '/images/weapons/sniperrifles/a19-argali.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhi9m8wl3zu0r',
  'Borealis',
  'borealis',
  4,
  'Sniper Rifle',
  1295,
  'Spread',
  'Arc',
  'Power',
  '/images/weapons/sniperrifles/borealis.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhpm0mh7z5ojs',
  'Izanagis Burden',
  'izanagis-burden',
  4,
  'Sniper Rifle',
  1030,
  'Piercing',
  'Arc',
  'Power',
  '/images/weapons/sniperrifles/izanagis-burden.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nho428e5tcva',
  'Magoichi',
  'magoichi',
  5,
  'Sniper Rifle',
  1343,
  'Impact',
  'Void',
  'Primary',
  '/images/weapons/sniperrifles/magoichi.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhtbg3qjx7g7a',
  'Overseer',
  'overseer',
  5,
  'Sniper Rifle',
  1403,
  'Spread',
  'Void',
  'Primary',
  '/images/weapons/sniperrifles/overseer.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhdrgjnca0a6',
  'The Accelerator',
  'the-accelerator',
  4,
  'Sniper Rifle',
  1288,
  'Rapid-Fire',
  'Solar',
  'Primary',
  '/images/weapons/sniperrifles/the-accelerator.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh8gjhgth716j',
  'The Ultimate Prey',
  'the-ultimate-prey',
  4,
  'Sniper Rifle',
  1486,
  'Rapid-Fire',
  'Arc',
  'Power',
  '/images/weapons/sniperrifles/the-ultimate-prey.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhho1yyq2hl5v',
  'Type 5 Stratoshot Srm',
  'type-5-stratoshot-srm',
  4,
  'Sniper Rifle',
  1039,
  'Impact',
  'Void',
  'Primary',
  '/images/weapons/sniperrifles/type-5-stratoshot-srm.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh2fiylpy3wbw',
  'Autoshear',
  'autoshear',
  6,
  'Submachine Gun',
  1070,
  'Rapid-Fire',
  'Arc',
  'Power',
  '/images/weapons/submachineguns/autoshear.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhvlkzy3wo9x',
  'Dancing Bees',
  'dancing-bees',
  3,
  'Submachine Gun',
  1441,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/submachineguns/dancing-bees.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhbeayaz874aq',
  'Del5 Kulfi',
  'del5-kulfi',
  5,
  'Submachine Gun',
  1224,
  'Rapid-Fire',
  'Void',
  'Primary',
  '/images/weapons/submachineguns/del5-kulfi.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhiblsy839oj7',
  'K18 Coelops',
  'k18-coelops',
  4,
  'Submachine Gun',
  1088,
  'Impact',
  'Solar',
  'Power',
  '/images/weapons/submachineguns/k18-coelops.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh9pdk0eag5el',
  'Riskrunner',
  'riskrunner',
  5,
  'Submachine Gun',
  1421,
  'Piercing',
  'Arc',
  'Power',
  '/images/weapons/submachineguns/riskrunner.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhchqx4tfemv',
  'The Huckleberry',
  'the-huckleberry',
  4,
  'Submachine Gun',
  1485,
  'Piercing',
  'Void',
  'Power',
  '/images/weapons/submachineguns/the-huckleberry.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nh2cudtujbwzr',
  'Wolfpack',
  'wolfpack',
  6,
  'Submachine Gun',
  1408,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/submachineguns/wolfpack.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhubpap42ysgr',
  'Cly2 Kakalik',
  'cly2-kakalik',
  6,
  'Sword',
  1425,
  'Impact',
  'Solar',
  'Primary',
  '/images/weapons/swords/cly2-kakalik.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhbd3g3sk66c',
  'Dusty Grave',
  'dusty-grave',
  4,
  'Sword',
  1415,
  'Piercing',
  'Arc',
  'Primary',
  '/images/weapons/swords/dusty-grave.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhe7s224ydxzb',
  'Makeshift Ending',
  'makeshift-ending',
  5,
  'Sword',
  1376,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/swords/makeshift-ending.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhohfxcmzw1er',
  'Nightfall Banner',
  'nightfall-banner',
  6,
  'Sword',
  1217,
  'Impact',
  'Arc',
  'Power',
  '/images/weapons/swords/nightfall-banner.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhg57bi8gv2zq',
  'Nobunaga',
  'nobunaga',
  5,
  'Sword',
  1400,
  'Piercing',
  'Arc',
  'Primary',
  '/images/weapons/swords/nobunaga.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhs7i078tgkgi',
  'Partridge Sky',
  'partridge-sky',
  6,
  'Sword',
  1373,
  'Impact',
  'Void',
  'Power',
  '/images/weapons/swords/partridge-sky.webp',
  NOW(),
  NOW()
);\n\nINSERT INTO "Weapon" (id, name, slug, rarity, "weaponType", "basePower", "combatStyle", element, slot, "imageUrl", "createdAt", "updatedAt") VALUES (
  'clmgevf6nhcf2tomcgsm',
  'Regolith Piton',
  'regolith-piton',
  6,
  'Sword',
  1284,
  'Impact',
  'Solar',
  'Primary',
  '/images/weapons/swords/regolith-piton.webp',
  NOW(),
  NOW()
);